export const LIST_ROW = '.list_item.symph_row'
export const LIST_NICKNAME = '.nickname'
export const LIST_STICKER = `${LIST_NICKNAME} > img`
export const LIST_SUBJECT = '.subject_fixed'
export const LIST_HIT = '.hit'
export const LIST_TIMESTAMP = '.timestamp'
export const LIST_CATEGORY = '.category.fixed'
export const LIST_PICTURE = '.icon_pic'
export const LIST_PO = '#po'

export const DETAIL_CATEGORY = '.post_subject > :nth-child(1)'
export const DETAIL_SUBJECT = '.post_subject > :nth-child(2)'
export const DETAIL_NICKNAME = '.post_contact .nickname'
export const DETAIL_STICKER = `${DETAIL_NICKNAME} > img`
export const DETAIL_VIEW_COUNT = '.view_info .view_count'
export const DETAIL_TIMESTAMP = '.post_author > :nth-child(1)'
export const DETAIL_IP = '.post_author > :nth-child(2)'
export const DETAIL_PRODUCT_INFO = '.market_product .product_info'
export const DETAIL_ARTICLE = '.post_article'
export const DETAIL_CONTACT_INFO = '.popup_contact td'

export const COMMENT_WRAPPER = '.post_comment'
export const COMMENT = '.comment_row'
export const COMMENT_NICKNAME = '.nickname'
export const COMMENT_TIMESTAMP = '.timestamp'
export const COMMENT_IP = '.ip_address'
export const COMMENT_CONTENT = '.comment_view'
export const COMMENT_LIKE_COUNT = '.comment_symph > strong'
