export const LIST_ROW = '.list_item.symph_row'
export const LIST_NICKNAME = '.nickname'
export const LIST_STICKER = `${LIST_NICKNAME} > img`
export const LIST_SUBJECT = '.subject_fixed'
export const LIST_HIT = '.hit'
export const LIST_TIMESTAMP = '.timestamp'
export const LIST_CATEGORY = '.category_fixed'
export const LIST_PO = '#po'

export const DETAIL_NICKNAME = '.post_info .nickname'
export const DETAIL_STICKER = `${DETAIL_NICKNAME} > img`
export const DETAIL_SUBJECT = '.post_subject > span:nth-child(2)'
export const DETAIL_VIEW_COUNT = '.view_count'
export const DETAIL_TIMESTAMP = '.post_author > span:first-child'
export const DETAIL_IP = '.post_author > span:last-child'
export const DETAIL_ARTICLE = '.post_article'
export const DETAIL_WRITER = '#writer'
export const DETAIL_CATEGORY = '.post_category'
export const DETAIL_PRODUCT_INFO = '.product_info'

export const COMMENT = '.comment_row'
export const COMMENT_NICKNAME = '.nickname'
export const COMMENT_TIMESTAMP = '.timestamp'
export const COMMENT_IP = '.ip_address'
export const COMMENT_CONTENT = '.comment_view'
export const COMMENT_LIKE_COUNT = '.comment_symph > strong'
